---

stages:
  - build
  - deploy

variables:
  RTSOPTS: "+RTS -N1 -s"
  CABAL_CONFIG: ${CI_PROJECT_DIR}/.cabal/config

build:
  stage: build
  except:
    - tags
  image:
    name: frankhjung/haskell:9.0.2
    entrypoint: [""]
  script:
    - make cleanall
    - mkdir .cabal/ public/
    - cabal user-config init
    - make setup all
    - mv -f -t public/
        ./dist-newstyle/build/x86_64-linux/ghc*/QuotesCSV*/doc/html/QuotesCSV/*
  artifacts:
    paths:
      - public/
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
      - dist/
      - dist-newstyle/

pages:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  image: alpine:latest
  script:
    - echo Publish documentation ...
  dependencies:
    - build
  artifacts:
    paths:
      - public
