---

stages:
  - build
  - deploy

variables:
  CABAL_CONFIG: ${CI_PROJECT_DIR}/.cabal/config
  TARGET: QuotesCSV
  RTSOPTS: "+RTS -N1"

build:
  except:
    - tags
  image:
    name: frankhjung/haskell:8.8.4
    entrypoint: [""]
  stage: build
  script:
    - mkdir -p public/ .cabal/
    - cabal user-config update
    - make setup check build test doc exec
    - cp -pr ./dist-newstyle/build/x86_64-linux/ghc*/QuotesCSV*/doc/html/QuotesCSV/* public/
  artifacts:
    paths:
      - public
  cache:
    key: ${CI_COMMIT_REF_NAME}-${CI_JOB_NAME}
    paths:
      - cabal.project.local
      - .cabal.config
      - dist-newstyle/

pages:
  only:
    refs:
      - master
  image: alpine:latest
  stage: deploy
  script:
    - echo Publishing pages ...
  dependencies:
    - build
  artifacts:
    paths:
      - public
