flags: {}
extra-deps:
  - hspec-2.5.6
  - hspec-core-2.5.6
  - hspec-discover-2.5.6
  - QuickCheck-2.12.1
  - text-1.2.3.0
packages:
  - .
# https://www.stackage.org/ ghc 8.2.2 => lts 11.22
resolver: lts-11.22
system-ghc: true
